version: 0.0
os: linux
files:
- source: /
  destination: /app
hooks:
  ApplicationStart:
  - location: scripts/application_start.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: scripts/application_stop.sh
    timeout: 300
    runas: root
